export const ENDPOINT = {
  API: {
    GET_ACCESS_TOKEN: '/v1/auth/user',
    GET_LIST_EMPLOYEE: '/v1/employee',
    EMPLOYEE_TYPES: '/v1/master-data/employee-types',
    DELETE_EMPLOYEE: '/v1/employee',
    GET_MY_PROFILE: '/v1/user/profile',
    UPDATE_MY_PROFILE: '/v1/user/profile',
    GET_EMPLOYEE_DETAIL: '/v1/employee',
    UPLOAD_AVATAR: '/v1/media/avatar',
    UPDATE_EMPLOYEE: '/v1/employee',
    CREATE_EMPLOYEE: '/v1/employee',
    FETCH_DATA_SLACK: '/v1/user/slack',
  },
  ROUTING: {
    AUTH: '/auth',
    SIGNUP: '/auth/register',
    LOGIN: '/auth/login',
    LOGIN_WITH_GOOGLE: '/v1/auth/google',
    LOGIN_SUCCESS: '/login/success',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    RESEND_VERIFY_EMAIL: '/auth/verify-email/resend',
    LOGOUT: '/auth/logout',
    DASHBOARD: '/dashboard',
    EMPLOYEE_LIST: '/employee-list',
    EMPLOYEE_DETAIL: '/employee-detail/:id',
    EMPLOYEE_EDIT: '/employee-edit/:id',
    EMPLOYEE_NEW: '/employee-new',
    EVALUATION: '/research-paper',
    EXAMINATION_LIST: '/sumarization',
    MY_PROFILE: '/my-profile',
    EDIT_MY_PROFILE: '/edit-my-profile',
    ERROR: '/error',
    ERROR_404: '/error/404',
  },
};
